export type ProcessLifecycleStatus = "draft" | "in_review" | "published" | "inactive" | "archived";
export type ProcessVersionStatus = "draft" | "in_review" | "published" | "retired";
export type ProcessSection = "library" | "modeler" | "mine" | "drafts" | "review" | "published" | "archived" | "history" | "settings";
export type ProcessPermissions = { view: boolean; manage: boolean; publish: boolean };
export type ProcessArea = { id: string; name: string; code: string; status: string; managerUserId: string };
export type ProcessMember = { id: string; name: string; email: string; role: string };
export type ProcessCompanyOption = { id: string; name: string; status: string };
export type ProcessTaskTemplate = { id:string; title:string; instructions:string; responsibilityMode:string; responsibleUserId:string; responsibleAreaId:string; evidenceRequired:boolean };
export type ProcessVersionSummary = { id:string; processId:string; processName:string; version:number; versionMajor:number; versionMinor:number; status:ProcessVersionStatus; revision:number; changeSummary:string; createdBy:string; createdByName:string; createdAt:string; updatedAt:string; publishedBy:string; publishedAt:string };
export type ProcessVersionDetail = { id:string; processId:string; processName:string; processCode:string; version:number; versionMajor:number; versionMinor:number; status:ProcessVersionStatus; revision:number; bpmnXml:string; svgPreview:string; configuration:Record<string,unknown>; changeSummary:string; createdAt:string; updatedAt:string; publishedAt:string; requirePublicationApproval:boolean };
export type ProcessDefinition = { id:string; code:string; name:string; description:string; objective:string; category:string; ownerDepartmentId:string; ownerDepartmentName:string; ownerUserId:string; ownerUserName:string; lifecycleStatus:ProcessLifecycleStatus; active:boolean; currentVersionId:string; isCorporate:boolean; allowManualStart:boolean; allowAutomaticStart:boolean; requirePublicationApproval:boolean; globalSlaValue:number; globalSlaUnit:"minutes"|"hours"|"days"; criticality:"low"|"medium"|"high"|"critical"; defaultPriority:"low"|"normal"|"high"|"urgent"; tags:string[]; notes:string; stepCount:number; companies:Array<{id:string;name:string}>; createdBy:string; updatedBy:string; updatedByName:string; createdAt:string; updatedAt:string; archivedAt:string; currentVersion:null|{id:string;version:number;versionMajor:number;versionMinor:number;status:ProcessVersionStatus;revision:number;bpmnXml:string;svgPreview:string;updatedAt:string;publishedAt:string} };
export type ProcessStepConfig = { id:string; bpmnElementId:string; stepType:string; departmentId:string; responsibleUserId:string; responsibilityMode:string; slaValue:number; slaUnit:"minutes"|"hours"|"days"; slaBusinessDays:boolean; cutoffTime:string; escalation:Record<string,unknown>; createDemand:boolean; demandType:string; requesterDepartmentId:string; responsibleDepartmentId:string; demandPriority:"low"|"normal"|"high"|"urgent"; demandSlaValue:number; demandSlaUnit:"minutes"|"hours"|"days"; checklistId:string; checklistItems:string[]; formId:string; requiredDocuments:string[]; optionalDocuments:string[]; evidenceRequired:boolean; requiresApproval:boolean; approverUserId:string; approverDepartmentId:string; approvalCount:number; approvalMode:"sequential"|"parallel"; subprocessProcessId:string; settings:{name:string;description:string;instructions:string;internalCode:string;dynamicAssignee:string;notificationTemplate:string;entryRules:ProcessCondition[];exitRules:ProcessCondition[];transitions:Record<string,ProcessCondition[]>;blockingIntegrations:string[];documentProof:"declared"|"attached";tasks?:ProcessTaskTemplate[]} };
/** Uma condição do §23/§25, do jeito que o modelador a edita. */
export type ProcessCondition = { field:string; operator:string; value:string };

export type ProcessOptions = { currentUserId:string; areas:ProcessArea[]; members:ProcessMember[]; companies:ProcessCompanyOption[] };
export type ProcessCatalogPayload = { processes:ProcessDefinition[]; versions:ProcessVersionSummary[]; nextCursor?:string|null; currentUserId:string; permissions:ProcessPermissions };
