-- Normalizes databases originally created by the legacy SQLite-compatible runtime.
ALTER TABLE "fdp_users" ADD COLUMN IF NOT EXISTS "password_hash" text;
ALTER TABLE "fdp_users" ADD COLUMN IF NOT EXISTS "password_salt" text;
ALTER TABLE "fdp_companies" ADD COLUMN IF NOT EXISTS "parent_company_id" text REFERENCES "fdp_companies"("id") ON DELETE SET NULL;
ALTER TABLE "fdp_companies" ADD COLUMN IF NOT EXISTS "is_principal" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_cards" ADD COLUMN IF NOT EXISTS "company_id" text REFERENCES "fdp_companies"("id") ON DELETE SET NULL;
ALTER TABLE "fdp_cards" ADD COLUMN IF NOT EXISTS "sla_target_minutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_cards" ADD COLUMN IF NOT EXISTS "sla_started_at" text;
ALTER TABLE "fdp_cards" ADD COLUMN IF NOT EXISTS "sla_paused_minutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_cards" ADD COLUMN IF NOT EXISTS "sla_pause_reason" text NOT NULL DEFAULT '';
ALTER TABLE "fdp_cards" ADD COLUMN IF NOT EXISTS "sla_escalation_level" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "headcount_start" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "headcount_end" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "leaves_count" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "voluntary_terminations" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "involuntary_terminations" integer NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "base_salary" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "variable_pay" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "overtime_pay" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "additional_pay" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "vacation_pay" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "thirteenth_pay" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "termination_pay" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "gross_payroll" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "employee_inss" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "employee_irrf" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "employee_other_deductions" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "net_pay" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "employer_inss" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "rat_contribution" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "third_party_contributions" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "fgts" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "fgts_penalty" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "employer_charges" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "benefits_cost" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "provisions_cost" double precision NOT NULL DEFAULT 0;
ALTER TABLE "fdp_hr_metrics" ADD COLUMN IF NOT EXISTS "other_costs" double precision NOT NULL DEFAULT 0;
--> statement-breakpoint
ALTER TABLE "fdp_users" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_access_recovery_tokens" ALTER COLUMN "expires_at" TYPE timestamptz USING "expires_at"::timestamptz;
ALTER TABLE "fdp_access_recovery_tokens" ALTER COLUMN "used_at" TYPE timestamptz USING NULLIF("used_at", '')::timestamptz;
ALTER TABLE "fdp_access_recovery_tokens" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_workspaces" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_companies" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_companies" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_workspace_members" ALTER COLUMN "joined_at" TYPE timestamptz USING "joined_at"::timestamptz;
ALTER TABLE "fdp_member_company_access" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_user_workspace_preferences" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_boards" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_cards" ALTER COLUMN "due_at" TYPE timestamptz USING NULLIF("due_at", '')::timestamptz;
ALTER TABLE "fdp_cards" ALTER COLUMN "sla_started_at" TYPE timestamptz USING NULLIF("sla_started_at", '')::timestamptz;
ALTER TABLE "fdp_cards" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_cards" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_checklist_items" ALTER COLUMN "completed_at" TYPE timestamptz USING NULLIF("completed_at", '')::timestamptz;
ALTER TABLE "fdp_card_comments" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_card_comments" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_custom_field_values" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_card_attachments" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_workspace_settings" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_business_holidays" ALTER COLUMN "holiday_date" TYPE date USING "holiday_date"::date;
ALTER TABLE "fdp_notifications" ALTER COLUMN "read_at" TYPE timestamptz USING NULLIF("read_at", '')::timestamptz;
ALTER TABLE "fdp_notifications" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_integrations" ALTER COLUMN "last_sync_at" TYPE timestamptz USING NULLIF("last_sync_at", '')::timestamptz;
ALTER TABLE "fdp_integrations" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_integrations" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_planner_blocks" ALTER COLUMN "start_at" TYPE timestamptz USING "start_at"::timestamptz;
ALTER TABLE "fdp_planner_blocks" ALTER COLUMN "end_at" TYPE timestamptz USING "end_at"::timestamptz;
ALTER TABLE "fdp_planner_blocks" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_planner_blocks" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_calendar_connections" ALTER COLUMN "last_sync_at" TYPE timestamptz USING NULLIF("last_sync_at", '')::timestamptz;
ALTER TABLE "fdp_calendar_connections" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_calendar_connections" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
ALTER TABLE "fdp_card_sla_pauses" ALTER COLUMN "started_at" TYPE timestamptz USING "started_at"::timestamptz;
ALTER TABLE "fdp_card_sla_pauses" ALTER COLUMN "ended_at" TYPE timestamptz USING NULLIF("ended_at", '')::timestamptz;
ALTER TABLE "fdp_workspace_inbox_items" ALTER COLUMN "received_at" TYPE timestamptz USING "received_at"::timestamptz;
ALTER TABLE "fdp_activity_events" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "created_at" TYPE timestamptz USING "created_at"::timestamptz;
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "updated_at" TYPE timestamptz USING "updated_at"::timestamptz;
--> statement-breakpoint
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "base_salary" TYPE numeric(18,2) USING round("base_salary"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "variable_pay" TYPE numeric(18,2) USING round("variable_pay"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "overtime_pay" TYPE numeric(18,2) USING round("overtime_pay"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "additional_pay" TYPE numeric(18,2) USING round("additional_pay"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "vacation_pay" TYPE numeric(18,2) USING round("vacation_pay"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "thirteenth_pay" TYPE numeric(18,2) USING round("thirteenth_pay"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "termination_pay" TYPE numeric(18,2) USING round("termination_pay"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "gross_payroll" TYPE numeric(18,2) USING round("gross_payroll"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "employee_inss" TYPE numeric(18,2) USING round("employee_inss"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "employee_irrf" TYPE numeric(18,2) USING round("employee_irrf"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "employee_other_deductions" TYPE numeric(18,2) USING round("employee_other_deductions"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "net_pay" TYPE numeric(18,2) USING round("net_pay"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "employer_inss" TYPE numeric(18,2) USING round("employer_inss"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "rat_contribution" TYPE numeric(18,2) USING round("rat_contribution"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "third_party_contributions" TYPE numeric(18,2) USING round("third_party_contributions"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "fgts" TYPE numeric(18,2) USING round("fgts"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "fgts_penalty" TYPE numeric(18,2) USING round("fgts_penalty"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "employer_charges" TYPE numeric(18,2) USING round("employer_charges"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "benefits_cost" TYPE numeric(18,2) USING round("benefits_cost"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "provisions_cost" TYPE numeric(18,2) USING round("provisions_cost"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "other_costs" TYPE numeric(18,2) USING round("other_costs"::numeric, 2);
ALTER TABLE "fdp_hr_metrics" ALTER COLUMN "payroll_cost" TYPE numeric(18,2) USING round("payroll_cost"::numeric, 2);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "fdp_cards_company_idx" ON "fdp_cards" ("company_id");
CREATE INDEX IF NOT EXISTS "fdp_companies_workspace_parent_idx" ON "fdp_companies" ("workspace_id", "parent_company_id");
