"use client";

import { FormEvent } from "react";
import { Download, Search } from "lucide-react";
import styles from "../platform.module.css";
import { Empty, ErrorState, FeatureHeader, FeatureProps, Loading, Panel, Row, Status, date, text, usePlatformResource } from "./core";

export function AuditFeature({ params, updateQuery }: FeatureProps) {
  const filters = { actor: params.get("actor") ?? "", entity: params.get("entity") ?? "", action: params.get("action") ?? "", requestId: params.get("requestId") ?? "", from: params.get("from") ?? "", to: params.get("to") ?? "", cursor: params.get("cursor") ?? "" };
  const query = new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([, value]) => value))); query.set("limit", "40");
  const resource = usePlatformResource<{ events: Row[]; nextCursor?: string }>(`/api/platform/audit?${query}`);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const actor = String(form.get("actor") ?? "").trim(); const requestId = String(form.get("requestId") ?? "").trim(); updateQuery({ actor: actor || null, requestId: requestId || null, cursor: null }); }
  const exportQuery = new URLSearchParams(query); exportQuery.delete("cursor"); exportQuery.set("format", "csv"); exportQuery.set("limit", "1000");
  return <><FeatureHeader eyebrow="TRILHA IMUTÁVEL" title="Auditoria" description="Ator, escopo, entidade, antes/depois saneados e request id." loading={resource.loading} onRefresh={resource.refresh} actions={<a className={styles.headerAction} href={`/api/platform/audit?${exportQuery}`}><Download aria-hidden="true" />Exportar CSV</a>} />
    <form key={`${filters.actor}:${filters.requestId}`} className={styles.auditFilters} onSubmit={submit}><label><Search aria-hidden="true" /><input name="actor" defaultValue={filters.actor} placeholder="Ator (e-mail)" /></label><input name="requestId" defaultValue={filters.requestId} placeholder="Request id" /><input value={filters.entity} onChange={(event) => updateQuery({ entity: event.target.value || null, cursor: null })} placeholder="Entidade" /><input value={filters.action} onChange={(event) => updateQuery({ action: event.target.value || null, cursor: null })} placeholder="Ação" /><input type="date" value={filters.from} onChange={(event) => updateQuery({ from: event.target.value || null, cursor: null })} aria-label="Data inicial" /><input type="date" value={filters.to} onChange={(event) => updateQuery({ to: event.target.value || null, cursor: null })} aria-label="Data final" /><button type="submit">Aplicar</button></form>
    {resource.loading && !resource.data ? <Loading /> : resource.error ? <ErrorState message={resource.error} retry={resource.refresh} /> : <Panel title="Eventos" subtitle="Valores sensíveis são redigidos antes de chegar ao navegador."><div className={styles.auditEvents}>{(resource.data?.events ?? []).map((row) => <details key={text(row.id)}><summary><Status value={text(row.outcome)} /><span><strong>{text(row.action)}</strong><small>{text(row.scope)} · {text(row.workspaceName)} · {text(row.actorEmail) || "sistema"}</small></span><time>{date(row.createdAt)}</time></summary><dl><div><dt>Entidade</dt><dd>{text(row.entityType)} · {text(row.entityId)}</dd></div><div><dt>Request id</dt><dd><code>{text(row.requestId) || "—"}</code></dd></div><div><dt>Antes</dt><dd><pre>{JSON.stringify(row.before, null, 2)}</pre></dd></div><div><dt>Depois</dt><dd><pre>{JSON.stringify(row.after, null, 2)}</pre></dd></div></dl></details>)}</div>{!(resource.data?.events?.length) && <Empty />}<div className={styles.pagination}><button disabled={!filters.cursor} onClick={() => updateQuery({ cursor: null })}>Primeira página</button><button disabled={!resource.data?.nextCursor} onClick={() => updateQuery({ cursor: resource.data?.nextCursor ?? null })}>Próxima página</button></div></Panel>}
  </>;
}
