"use client";

import { FormEvent, useState } from "react";
import { Pencil } from "lucide-react";
import styles from "../platform.module.css";
import { Empty, ErrorState, FeatureHeader, FeatureProps, Loading, MetricCard, Notice, Panel, Row, Status, date, money, number, platformRequest, text, usePlatformResource } from "./core";

export function BillingFeature({ params, updateQuery }: FeatureProps) {
  const resource = usePlatformResource<Row>("/api/platform/billing"); const overview = usePlatformResource<{ plans: Row[] }>("/api/platform/overview");
  const leadStatus = params.get("leadStatus") ?? ""; const leadCursor = params.get("leadCursor") ?? "";
  const leads = usePlatformResource<{ leads: Row[]; nextCursor?: string }>(`/api/platform/leads?${new URLSearchParams({ ...(leadStatus ? { status: leadStatus } : {}), ...(leadCursor ? { cursor: leadCursor } : {}), limit: "30" })}`);
  const [editingPlan, setEditingPlan] = useState<Row | null>(null); const [notice, setNotice] = useState("");
  const metrics = (resource.data?.metrics ?? {}) as Row; const invoices = (resource.data?.invoices ?? {}) as Row; const events = (resource.data?.webhookEvents ?? {}) as Row; const configuration = (resource.data?.configuration ?? {}) as Row;
  const unavailable = [["Variação de MRR", metrics.mrrChange], ["Churn de receita", metrics.revenueChurn], ["LTV", metrics.ltv]] as [string, unknown][];
  const refresh = () => { resource.refresh(); overview.refresh(); leads.refresh(); };
  return <><FeatureHeader eyebrow="RECEITA E COBRANÇA" title="Financeiro" description="MRR contratado, inadimplência, planos, faturas, webhooks e pipeline comercial." loading={resource.loading} onRefresh={refresh} />{notice && <Notice>{notice}</Notice>}
    {resource.loading && !resource.data ? <Loading /> : resource.error ? <ErrorState message={resource.error} retry={refresh} /> : <><section className={styles.metricGrid}><MetricCard label="MRR" value={money(metrics.mrrCents)} note="Assinaturas ativas" tone="safe" /><MetricCard label="Receita em risco" value={money(metrics.revenueAtRiskCents)} tone={number(metrics.revenueAtRiskCents) ? "danger" : "safe"} /><MetricCard label="Conversão de trial" value={metrics.trialConversionRate == null ? "—" : `${number(metrics.trialConversionRate)}%`} /><MetricCard label="ARPA" value={metrics.arpaCents == null ? "—" : money(metrics.arpaCents)} /></section>
      <div className={styles.twoColumns}><Panel title="Definições" subtitle="Fórmulas exibidas junto dos números."><dl className={styles.definitionList}>{Object.entries((resource.data?.definitions ?? {}) as Row).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{text(value)}</dd></div>)}</dl></Panel><Panel title="Dados insuficientes"><dl className={styles.definitionList}>{unavailable.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{text((value as Row)?.reason) || "Indisponível"}</dd></div>)}</dl></Panel></div>
      <Panel title="Planos publicados" subtitle="Alteração de preço cria uma nova versão; contratos antigos preservam o valor contratado."><div className={styles.cardGrid}>{(overview.data?.plans ?? []).map((plan) => <article key={text(plan.id)}><header><strong>{text(plan.name)}</strong><Status value={text(plan.status)} /></header><p>{text(plan.description)}</p><dl><div><dt>Mensal</dt><dd>{money(plan.monthlyPriceCents)}</dd></div><div><dt>Assentos</dt><dd>{number(plan.includedSeats)}</dd></div><div><dt>Empresas</dt><dd>{number(plan.companyLimit)}</dd></div></dl><button type="button" className={styles.smallAction} onClick={() => setEditingPlan(plan)}><Pencil aria-hidden="true" />Editar plano</button></article>)}</div></Panel>
      <Panel title="Faturas recentes" subtitle="Valores e status persistidos pelo subsistema de cobrança."><div className={styles.tableWrap}><table><thead><tr><th>Workspace</th><th>Status</th><th>Valor devido</th><th>Valor pago</th><th>Período</th></tr></thead><tbody>{(Array.isArray(invoices.recent) ? invoices.recent as Row[] : []).map((row) => <tr key={text(row.id)}><td>{text(row.workspace_name)}</td><td><Status value={text(row.status)} /></td><td>{money(row.amount_due_cents, text(row.currency) || "BRL")}</td><td>{money(row.amount_paid_cents, text(row.currency) || "BRL")}</td><td>{date(row.period_ends_at)}</td></tr>)}</tbody></table></div>{!(Array.isArray(invoices.recent) && invoices.recent.length) && <Empty />}</Panel>
      <div className={styles.twoColumns}><Panel title="Eventos de cobrança" subtitle="Webhook por estado."><dl className={styles.counterList}>{Object.entries((events.totals ?? {}) as Row).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{number(value)}</dd></div>)}</dl></Panel><Panel title="Configuração" subtitle="Somente presença; nenhum segredo é exibido."><dl className={styles.counterList}>{Object.entries(configuration).map(([key, value]) => <div key={key}><dt>{key}</dt><dd><Status value={value ? "ready" : "missing"} /></dd></div>)}</dl></Panel></div></>}
    <Panel title="Leads comerciais" subtitle="Contatos do site, com detalhe e andamento auditado."><div className={styles.filterBar}><select value={leadStatus} onChange={(event) => updateQuery({ leadStatus: event.target.value || null, leadCursor: null })} aria-label="Filtrar leads"><option value="">Todos</option><option value="new">Novos</option><option value="contacted">Contatados</option><option value="qualified">Qualificados</option><option value="discarded">Descartados</option></select></div>{leads.loading && !leads.data ? <Loading /> : leads.error ? <ErrorState message={leads.error} retry={leads.refresh} /> : <><div className={styles.tableWrap}><table><thead><tr><th>Contato</th><th>Empresa</th><th>Interesse</th><th>Recebido</th><th>Andamento</th></tr></thead><tbody>{(leads.data?.leads ?? []).map((lead) => <LeadRow key={text(lead.id)} lead={lead} onChanged={() => { setNotice("Andamento comercial atualizado e auditado."); leads.refresh(); resource.refresh(); }} />)}</tbody></table></div>{!(leads.data?.leads.length) && <Empty />}<div className={styles.pagination}><button disabled={!leadCursor} onClick={() => updateQuery({ leadCursor: null })}>Primeira página</button><button disabled={!leads.data?.nextCursor} onClick={() => updateQuery({ leadCursor: leads.data?.nextCursor ?? null })}>Próxima página</button></div></>}</Panel>
    {editingPlan && <PlanDialog plan={editingPlan} onClose={() => setEditingPlan(null)} onSaved={() => { setEditingPlan(null); setNotice("Plano atualizado, com nova versão de preço quando aplicável."); overview.refresh(); resource.refresh(); }} />}
  </>;
}

function LeadRow({ lead, onChanged }: { lead: Row; onChanged: () => void }) {
  const [status, setStatus] = useState(text(lead.status)); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function save() { setBusy(true); setError(""); try { await platformRequest("/api/platform/leads", { method: "PATCH", body: JSON.stringify({ id: lead.id, status }) }); onChanged(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao atualizar lead."); } finally { setBusy(false); } }
  return <tr><td><details><summary><strong>{text(lead.name)}</strong><small>{text(lead.email)}{text(lead.phone) ? ` · ${text(lead.phone)}` : ""}</small></summary><p>{text(lead.message) || "Sem mensagem."}</p></details>{error && <small className={styles.itemError}>{error}</small>}</td><td>{text(lead.company) || "—"}<small>{text(lead.headcount) ? `${text(lead.headcount)} pessoas` : ""}</small></td><td>{text(lead.interest) || "—"}</td><td>{date(lead.created_at)}</td><td><div className={styles.rowActions}><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label={`Andamento de ${text(lead.name)}`}><option value="new">Novo</option><option value="contacted">Contatado</option><option value="qualified">Qualificado</option><option value="discarded">Descartado</option></select><button type="button" disabled={busy || status === text(lead.status)} onClick={save}>{busy ? "Salvando…" : "Salvar"}</button></div></td></tr>;
}

function PlanDialog({ plan, onClose, onSaved }: { plan: Row; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const data = new FormData(event.currentTarget); const field = (name: string) => String(data.get(name) ?? "").trim(); const integer = (name: string) => Number(field(name)); await platformRequest(`/api/platform/plans/${encodeURIComponent(text(plan.id))}`, { method: "PATCH", body: JSON.stringify({ status: field("status"), monthlyPriceCents: integer("monthlyPriceCents"), annualPriceCents: integer("annualPriceCents"), trialDays: integer("trialDays"), includedSeats: integer("includedSeats"), companyLimit: integer("companyLimit"), integrationLimit: integer("integrationLimit"), storageLimitMb: integer("storageLimitMb"), features: field("features").split(",").map((item) => item.trim()).filter(Boolean), stripeMonthlyPriceId: field("stripeMonthlyPriceId"), stripeAnnualPriceId: field("stripeAnnualPriceId"), reason: field("reason"), confirmed: data.get("confirmed") === "on" }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao atualizar plano."); } finally { setBusy(false); } }
  const features = Array.isArray(plan.features) ? plan.features.join(", ") : "";
  return <div className={styles.dialogBackdrop}><form className={`${styles.actionDialog} ${styles.wideDialog}`} role="dialog" aria-modal="true" aria-labelledby="edit-plan" onSubmit={submit}><header><div><span>CATÁLOGO COMERCIAL</span><h2 id="edit-plan">Editar {text(plan.name)}</h2></div><button type="button" onClick={onClose} disabled={busy} aria-label="Fechar">×</button></header><div className={styles.formGrid}><label>Status<select name="status" defaultValue={text(plan.status)}><option value="draft">Rascunho</option><option value="active">Ativo</option><option value="archived">Arquivado</option></select></label><label>Teste (dias)<input name="trialDays" type="number" min={0} max={90} defaultValue={number(plan.trialDays)} required /></label><label>Preço mensal (centavos)<input name="monthlyPriceCents" type="number" min={0} defaultValue={number(plan.monthlyPriceCents)} required /></label><label>Preço anual (centavos)<input name="annualPriceCents" type="number" min={0} defaultValue={number(plan.annualPriceCents)} required /></label><label>Assentos incluídos<input name="includedSeats" type="number" min={1} defaultValue={number(plan.includedSeats)} required /></label><label>Limite de empresas<input name="companyLimit" type="number" min={1} defaultValue={number(plan.companyLimit)} required /></label><label>Limite de integrações<input name="integrationLimit" type="number" min={0} defaultValue={number(plan.integrationLimit)} required /></label><label>Armazenamento (MB)<input name="storageLimitMb" type="number" min={1} defaultValue={number(plan.storageLimitMb)} required /></label><label>Price ID mensal<input name="stripeMonthlyPriceId" defaultValue={text(plan.stripeMonthlyPriceId)} /></label><label>Price ID anual<input name="stripeAnnualPriceId" defaultValue={text(plan.stripeAnnualPriceId)} /></label><label className={styles.fullField}>Recursos (separados por vírgula)<textarea name="features" rows={3} defaultValue={features} /></label><label className={styles.fullField}>Motivo da alteração<textarea name="reason" rows={3} required minLength={5} /></label><label className={`${styles.fullField} ${styles.confirmCheck}`}><input name="confirmed" type="checkbox" required />Confirmo os novos limites, preços e efeitos no catálogo.</label>{error && <p className={`${styles.dialogError} ${styles.fullField}`} role="alert">{error}</p>}</div><footer><button type="button" onClick={onClose} disabled={busy}>Cancelar</button><button type="submit" disabled={busy}>{busy ? "Salvando…" : "Salvar plano"}</button></footer></form></div>;
}
