"use client";

import { FormEvent, useState } from "react";
import { Ban, Building2, CheckCircle2, ChevronRight, Plus, Search, Settings2, Trash2, UserRoundCheck } from "lucide-react";
import styles from "../platform.module.css";
import { AdminAction, AdminActionDialog, Empty, ErrorState, FeatureHeader, FeatureProps, Loading, Notice, Panel, Row, Status, date, number, platformRequest, text, usePlatformResource } from "./core";

export function ClientsFeature({ params, updateQuery }: FeatureProps) {
  const query = params.get("q") ?? ""; const status = params.get("status") ?? ""; const cursor = params.get("cursor") ?? ""; const selected = params.get("workspace") ?? "";
  const [action, setAction] = useState<AdminAction | null>(null); const [notice, setNotice] = useState(""); const [creating, setCreating] = useState(false);
  const url = `/api/platform/workspaces?${new URLSearchParams({ ...(query ? { q: query } : {}), ...(status ? { status } : {}), ...(cursor ? { cursor } : {}), limit: "30" })}`;
  const resource = usePlatformResource<{ workspaces: Row[]; nextCursor?: string }>(url);
  const overview = usePlatformResource<{ plans: Row[] }>("/api/platform/overview");
  const plans = overview.data?.plans ?? [];
  const refresh = () => { resource.refresh(); overview.refresh(); };
  function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const value = String(new FormData(event.currentTarget).get("q") ?? "").trim(); updateQuery({ q: value || null, cursor: null }); }
  function statusAction(row: Row) { const next = text(row.status) === "active" ? "suspended" : "active"; const name = text(row.name); setAction({ title: `${next === "active" ? "Reativar" : "Suspender"} ${name}`, consequence: next === "active" ? "O workspace voltará a aceitar acesso e operação conforme o plano contratado." : "O acesso ao workspace será interrompido para todos os membros até uma reativação explícita. Os dados serão preservados.", confirmLabel: next === "active" ? "Reativar workspace" : "Suspender workspace", run: async ({ reason }) => { await platformRequest(`/api/platform/workspaces/${encodeURIComponent(text(row.id))}`, { method: "PATCH", body: JSON.stringify({ status: next, reason, confirmed: true }) }); setNotice(`Workspace ${name} ${next === "active" ? "reativado" : "suspenso"}.`); refresh(); } }); }
  return <><FeatureHeader eyebrow="CADASTRO E CONTRATO" title="Clientes" description="Workspaces, proprietários, plano, capacidade, configuração e ciclo de vida." loading={resource.loading} onRefresh={refresh} actions={<button type="button" className={styles.headerAction} onClick={() => setCreating(true)}><Plus aria-hidden="true" />Novo workspace</button>} />
    {notice && <Notice>{notice}</Notice>}
    <form key={query} className={styles.filterBar} onSubmit={search}><label><Search aria-hidden="true" /><input name="q" defaultValue={query} placeholder="Nome, slug ou CNPJ" aria-label="Buscar clientes" /></label><select value={status} onChange={(event) => updateQuery({ status: event.target.value || null, cursor: null })} aria-label="Filtrar situação"><option value="">Todos os status</option><option value="active">Ativos</option><option value="suspended">Suspensos</option><option value="canceled">Cancelados</option><option value="archived">Arquivados</option></select><button type="submit">Buscar</button></form>
    {resource.loading && !resource.data ? <Loading /> : resource.error ? <ErrorState message={resource.error} retry={refresh} /> : <Panel title="Workspaces" subtitle="Lista paginada por cursor, ordenada por criação."><div className={styles.tableWrap}><table><thead><tr><th>Cliente</th><th>Proprietário</th><th>Plano</th><th>Uso</th><th>Status</th><th>Ações</th></tr></thead><tbody>{(resource.data?.workspaces ?? []).map((row) => <tr key={text(row.id)}><td><button className={styles.rowLink} onClick={() => updateQuery({ workspace: text(row.id) })}><Building2 aria-hidden="true" /><span><strong>{text(row.name)}</strong><small>{text(row.slug)}</small></span><ChevronRight aria-hidden="true" /></button></td><td><strong>{text(row.owner_name)}</strong><small>{text(row.owner_email)}</small></td><td><strong>{text(row.plan_name) || "Sem plano"}</strong><small>{text(row.subscription_status)}</small></td><td>{number(row.seats_used)}/{Math.max(number(row.seat_quantity), number(row.included_seats))} assentos<br />{number(row.companies)} empresas</td><td><Status value={text(row.status) || "active"} /></td><td><button className={styles.smallAction} onClick={() => statusAction(row)}>{text(row.status) === "active" ? <Ban aria-hidden="true" /> : <CheckCircle2 aria-hidden="true" />}{text(row.status) === "active" ? "Suspender" : "Reativar"}</button></td></tr>)}</tbody></table></div>{!(resource.data?.workspaces?.length) && <Empty />}
      <div className={styles.pagination}><button type="button" disabled={!cursor} onClick={() => updateQuery({ cursor: null })}>Primeira página</button><button type="button" disabled={!resource.data?.nextCursor} onClick={() => updateQuery({ cursor: resource.data?.nextCursor ?? null })}>Próxima página</button></div></Panel>}
    <Panel title="Catálogo de planos" subtitle="Capacidade e preços publicados; identificadores de provedor são públicos."><div className={styles.cardGrid}>{plans.map((plan) => <article key={text(plan.id)}><header><strong>{text(plan.name)}</strong><Status value={text(plan.status)} /></header><p>{text(plan.description)}</p><dl><div><dt>Mensal</dt><dd>{number(plan.monthlyPriceCents) / 100} BRL</dd></div><div><dt>Assentos</dt><dd>{number(plan.includedSeats)}</dd></div><div><dt>Integrações</dt><dd>{number(plan.integrationLimit)}</dd></div></dl></article>)}</div></Panel>
    {selected && <WorkspaceDetail id={selected} plans={plans} onClose={() => updateQuery({ workspace: null })} onConfigure={() => updateQuery({ area: "operations", workspace: selected })} onChanged={() => { setNotice("Workspace atualizado e evento de auditoria registrado."); refresh(); }} />}
    {creating && <CreateWorkspaceDialog plans={plans} onClose={() => setCreating(false)} onCreated={(id) => { setCreating(false); setNotice("Workspace, proprietário, assinatura e padrões criados em uma transação."); refresh(); updateQuery({ workspace: id }); }} />}
    <AdminActionDialog action={action} onClose={() => setAction(null)} />
  </>;
}

function WorkspaceDetail({ id, plans, onClose, onConfigure, onChanged }: { id: string; plans: Row[]; onClose: () => void; onConfigure: () => void; onChanged: () => void }) {
  const resource = usePlatformResource<Row>(`/api/platform/workspaces/${encodeURIComponent(id)}/detail`); const [action, setAction] = useState<AdminAction | null>(null); const [planCode, setPlanCode] = useState("");
  const workspace = (resource.data?.workspace ?? {}) as Row; const plan = (workspace.plan ?? {}) as Row; const owner = (workspace.owner ?? {}) as Row; const subscription = (workspace.subscription ?? {}) as Row;
  const mutate = (title: string, consequence: string, body: Row, confirmLabel: string, options: Partial<AdminAction> = {}) => setAction({ title, consequence, confirmLabel, ...options, run: async ({ reason, confirmation, value }) => { const payload = { ...body, reason, confirmed: true, ...(confirmation ? { confirmation } : {}), ...(value ? { ownerEmail: value } : {}) }; await platformRequest(`/api/platform/workspaces/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(payload) }); resource.refresh(); onChanged(); } });
  const currentPlan = planCode || text(plan.code);
  const status = text(workspace.status);
  // A exclusão definitiva só é liberada fora de operação. Antes, quando isto era
  // falso, o bloco inteiro sumia — e "não vejo o botão de excluir" virava um
  // chamado. Agora o bloco aparece sempre; o que muda é o botão estar habilitado
  // ou não, com a dica dizendo o que falta. A regra continua sendo do backend.
  const canPurge = ["archived", "canceled"].includes(status);
  return <><div className={styles.detailOverlay}><aside className={styles.detailPane} role="dialog" aria-modal="true" aria-labelledby="workspace-detail"><header><div><span>CLIENTE</span><h2 id="workspace-detail">{text(workspace.name) || "Carregando…"}</h2></div><button onClick={onClose}>Fechar</button></header>{resource.loading ? <Loading /> : resource.error ? <ErrorState message={resource.error} retry={resource.refresh} /> : <div className={styles.detailBody}>
    <dl className={styles.detailGrid}><div><dt>Status</dt><dd><Status value={status} /></dd></div><div><dt>Slug</dt><dd>{text(workspace.slug)}</dd></div><div><dt>Proprietário</dt><dd>{text(owner.name)}<small>{text(owner.email)}</small></dd></div><div><dt>Plano</dt><dd>{text(plan.name)}</dd></div><div><dt>Assinatura</dt><dd>{text(subscription.status)}<small>{text(subscription.provider)}</small></dd></div><div><dt>Criado</dt><dd>{date(workspace.createdAt)}</dd></div><div><dt>Razão social</dt><dd>{text(workspace.legalName) || "—"}<small>{text(workspace.taxId) || "Sem CNPJ"}</small></dd></div><div><dt>Contato</dt><dd>{text(workspace.contactEmail) || "—"}</dd></div></dl>
    <section className={styles.detailActions}><h3><Settings2 aria-hidden="true" />Configuração operacional</h3><p>Administre empresas, fluxo, campos, templates, SLA, automações, acessos, módulos, chaves e webhooks no contexto deste cliente.</p><button type="button" className={styles.smallAction} onClick={onConfigure}><Settings2 aria-hidden="true" />Administrar configuração</button></section>
    <section className={styles.detailActions}><h3>Plano e limites</h3><p>O servidor recusa downgrade abaixo do consumo atual e cria trilha antes/depois.</p><div className={styles.rowActions}><select value={currentPlan} onChange={(event) => setPlanCode(event.target.value)} aria-label="Novo plano">{plans.map((item) => <option key={text(item.code)} value={text(item.code)}>{text(item.name)}</option>)}</select><button type="button" disabled={!currentPlan || currentPlan === text(plan.code)} onClick={() => mutate(`Alterar plano de ${text(workspace.name)}`, "A assinatura passará a usar os limites e o preço publicado do plano selecionado. Nenhum usuário será removido automaticamente.", { planCode: currentPlan }, "Aplicar plano")}>Aplicar plano</button></div></section>
    <section className={styles.detailActions}><h3><UserRoundCheck aria-hidden="true" />Propriedade</h3><p>O novo proprietário precisa ter uma identidade ativa e receberá papel administrativo neste workspace.</p><button type="button" className={styles.smallAction} onClick={() => mutate(`Transferir ${text(workspace.name)}`, "A propriedade do cliente e a responsabilidade administrativa serão transferidas. O proprietário anterior não é removido automaticamente.", {}, "Transferir propriedade", { extraInput: { label: "E-mail do novo proprietário", type: "email", placeholder: "pessoa@empresa.com" } })}>Transferir propriedade</button></section>
    <section className={styles.detailActions}><h3>Ciclo de vida</h3><p>Suspender, cancelar e arquivar preservam os dados. Exclusão definitiva fica separada e nunca é automática.</p><div className={styles.rowActions}>{["active", "suspended", "canceled", "archived"].filter((next) => next !== status).map((next) => <button type="button" key={next} data-danger={next === "active" ? undefined : "true"} onClick={() => mutate(`${next === "active" ? "Reativar" : next === "suspended" ? "Suspender" : next === "canceled" ? "Cancelar" : "Arquivar"} ${text(workspace.name)}`, next === "active" ? "O acesso e a operação voltarão a ser permitidos." : "O estado do cliente mudará, mas dados, auditoria e histórico serão preservados.", { status: next }, "Confirmar alteração")}>{next}</button>)}</div><div className={styles.dangerZone}><strong>Exclusão definitiva</strong><p>Apaga os dados do workspace e registra previamente as contagens removidas. Use apenas por solicitação formal.</p>{!canPurge && <p className={styles.dangerHint} role="note">Arquive ou cancele o cliente antes de excluir: a exclusão definitiva só é liberada quando ele está fora de operação.</p>}<button type="button" disabled={!canPurge} title={canPurge ? undefined : "Arquive ou cancele o cliente para liberar a exclusão."} onClick={() => setAction({ title: `Excluir definitivamente ${text(workspace.name)}`, consequence: "Esta operação é irreversível. Todos os dados do workspace e identidades órfãs elegíveis serão removidos; somente o registro de exclusão permanecerá.", confirmLabel: "Excluir definitivamente", reasonMinLength: 10, typedConfirmation: text(workspace.slug), run: async ({ reason, confirmation }) => { await platformRequest(`/api/platform/workspaces/${encodeURIComponent(id)}/delete`, { method: "POST", body: JSON.stringify({ reason, confirmation, confirmed: true }) }); onChanged(); onClose(); } })}><Trash2 aria-hidden="true" />Excluir definitivamente</button></div></section>
    <DetailRows title="Membros" rows={resource.data?.members} /><DetailRows title="Empresas" rows={resource.data?.companies} /><DetailRows title="Módulos" rows={resource.data?.modules} /><DetailRows title="Auditoria" rows={resource.data?.audit} />
  </div>}</aside></div><AdminActionDialog action={action} onClose={() => setAction(null)} /></>;
}

function DetailRows({ title, rows }: { title: string; rows: unknown }) { const list = Array.isArray(rows) ? rows as Row[] : []; return <section className={styles.detailSection}><h3>{title}</h3>{list.length ? list.slice(0, 20).map((row, index) => <article key={text(row.id ?? row.userId ?? row.key) || index}><strong>{text(row.name ?? row.email ?? row.legalName ?? row.action ?? row.key)}</strong><small>{text(row.role ?? row.status ?? row.category ?? row.createdAt)}</small></article>) : <Empty />}</section>; }

function CreateWorkspaceDialog({ plans, onClose, onCreated }: { plans: Row[]; onClose: () => void; onCreated: (id: string) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { const data = new FormData(event.currentTarget); const field = (name: string) => String(data.get(name) ?? "").trim(); const payload = await platformRequest<{ workspace: { id: string } }>("/api/platform/workspaces", { method: "POST", body: JSON.stringify({ name: field("name"), slug: field("slug"), planCode: field("planCode"), legalName: field("legalName"), taxId: field("taxId"), contactEmail: field("contactEmail"), ownerName: field("ownerName"), ownerEmail: field("ownerEmail"), reason: field("reason"), confirmed: data.get("confirmed") === "on" }) }); onCreated(payload.workspace.id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao criar workspace."); } finally { setBusy(false); } }
  return <div className={styles.dialogBackdrop}><form className={`${styles.actionDialog} ${styles.wideDialog}`} role="dialog" aria-modal="true" aria-labelledby="create-workspace" onSubmit={submit}><header><div><span>PROVISIONAMENTO TRANSACIONAL</span><h2 id="create-workspace">Novo workspace</h2></div><button type="button" onClick={onClose} disabled={busy} aria-label="Fechar">×</button></header><div className={styles.formGrid}><label>Nome do workspace<input name="name" required minLength={2} maxLength={120} autoFocus /></label><label>Slug opcional<input name="slug" maxLength={60} /></label><label>Plano<select name="planCode" defaultValue={text(plans[0]?.code) || "starter"}>{plans.map((plan) => <option key={text(plan.code)} value={text(plan.code)}>{text(plan.name)}</option>)}</select></label><label>Razão social<input name="legalName" maxLength={200} /></label><label>CNPJ<input name="taxId" maxLength={20} /></label><label>Contato do grupo<input name="contactEmail" type="email" maxLength={180} /></label><label>Nome do proprietário<input name="ownerName" maxLength={160} /></label><label>E-mail do proprietário<input name="ownerEmail" type="email" required maxLength={180} /></label><label className={styles.fullField}>Motivo do provisionamento<textarea name="reason" required minLength={5} rows={3} /></label><label className={`${styles.fullField} ${styles.confirmCheck}`}><input name="confirmed" type="checkbox" required />Confirmo a criação do cliente, proprietário, assinatura e configuração inicial.</label>{error && <p className={`${styles.dialogError} ${styles.fullField}`} role="alert">{error}</p>}</div><footer><button type="button" onClick={onClose} disabled={busy}>Cancelar</button><button type="submit" disabled={busy}>{busy ? "Criando…" : "Criar workspace"}</button></footer></form></div>;
}
