"use client";

import styles from "../platform.module.css";
import { Empty, ErrorState, FeatureHeader, Loading, MetricCard, Panel, Row, Status, date, number, text, usePlatformResource } from "./core";

export function HealthFeature() {
  const resource = usePlatformResource<Row>("/api/platform/health"); const readiness = (resource.data?.readiness ?? {}) as Row; const database = (resource.data?.database ?? {}) as Row; const scheduler = (resource.data?.scheduler ?? {}) as Row; const integrations = (resource.data?.integrations ?? {}) as Row; const deployment = (resource.data?.deployment ?? {}) as Row; const services = (resource.data?.services ?? {}) as Row;
  return <><FeatureHeader eyebrow="PRONTIDÃO DO SISTEMA" title="Saúde" description="Banco, migrações, serviços, integração e atividade do scheduler sem dados decorativos." loading={resource.loading} onRefresh={resource.refresh} />
    {resource.loading && !resource.data ? <Loading /> : resource.error && !resource.data ? <ErrorState message={resource.error} retry={resource.refresh} /> : <><section className={styles.metricGrid}><MetricCard label="Readiness" value={<Status value={text(readiness.status)} />} note={text(readiness.detail)} tone={text(readiness.status) === "ok" ? "safe" : "danger"} /><MetricCard label="Banco" value={<Status value={text(database.status)} />} note={date(database.checkedAt)} /><MetricCard label="Integrações" value={`${number(integrations.active)}/${number(integrations.total)}`} note={`${number(integrations.attention)} exigem atenção`} /><MetricCard label="Dead-letter" value={number(scheduler.deadLetter)} note={`${number(scheduler.queued)} na fila`} tone={number(scheduler.deadLetter) ? "danger" : "safe"} /></section>
      <div className={styles.twoColumns}><Panel title="Migrações" subtitle="Resultado do verificador de schema desta versão."><div className={styles.healthBlock}><Status value={text(readiness.database) || text(readiness.status)} /><p>{text(readiness.detail)}</p>{Array.isArray(readiness.pendingMigrations) && readiness.pendingMigrations.length > 0 && <ul>{(readiness.pendingMigrations as unknown[]).map((item) => <li key={text(item)}>{text(item)}</li>)}</ul>}</div></Panel><Panel title="Deployment"><dl className={styles.definitionList}><div><dt>Ambiente</dt><dd>{text(deployment.environment)}</dd></div><div><dt>Commit</dt><dd><code>{text(deployment.commit)}</code></dd></div><div><dt>Verificado</dt><dd>{date(deployment.checkedAt)}</dd></div></dl></Panel></div>
      <Panel title="Capacidades configuradas" subtitle="Somente presença de configuração; valores nunca são retornados."><div className={styles.serviceGrid}>{Object.entries(services).map(([key, value]) => <article key={key}><Status value={value ? "ready" : "missing"} /><strong>{key}</strong></article>)}</div></Panel>
      <Panel title="Atividade do scheduler"><div className={styles.healthBlock}><Status value={scheduler.available ? "ready" : "unavailable"} /><p>{text(scheduler.note)}</p><small>Último job persistido: {date(scheduler.lastJobCreatedAt)}</small></div>{!scheduler.available && <Empty>O console não afirma que o scheduler está saudável sem evidência de atividade persistida.</Empty>}</Panel></>}
  </>;
}
