"use client";

import styles from "../platform.module.css";
import { Empty, ErrorState, FeatureHeader, Loading, MetricCard, Panel, Row, Status, date, number, text, usePlatformResource } from "./core";

export function SecurityFeature() {
  const resource = usePlatformResource<Row>("/api/platform/security"); const list = (key: string) => Array.isArray(resource.data?.[key]) ? resource.data?.[key] as Row[] : [];
  return <><FeatureHeader eyebrow="ACESSO E EXPOSIÇÃO" title="Segurança" description="Identidades bloqueadas, sessões, credenciais públicas, chaves e webhooks." loading={resource.loading} onRefresh={resource.refresh} />
    {resource.loading && !resource.data ? <Loading /> : resource.error ? <ErrorState message={resource.error} retry={resource.refresh} /> : <><section className={styles.metricGrid}><MetricCard label="Usuários bloqueados" value={list("blockedUsers").length} tone={list("blockedUsers").length ? "danger" : "safe"} /><MetricCard label="Ativação pendente" value={list("pendingActivation").length} tone={list("pendingActivation").length ? "warning" : "safe"} /><MetricCard label="Sessões ativas" value={list("activeSessions").length} /><MetricCard label="Credenciais ativas" value={list("credentials").length} /></section>
      <div className={styles.twoColumns}><Capability title="MFA e recuperação" data={resource.data?.mfa as Row} /><Capability title="Suporte assistido" data={resource.data?.assistedSupport as Row} /><Capability title="Falhas de autenticação" data={resource.data?.authenticationFailures as Row} /></div>
      <Panel title="Sessões ativas" subtitle="Sem token ou endereço completo."><SimpleTable rows={list("activeSessions")} columns={[["email", "Identidade"], ["device_label", "Dispositivo"], ["last_seen_at", "Última atividade"], ["expires_at", "Expira"]]} dates={new Set(["last_seen_at", "expires_at"])} /></Panel>
      <Panel title="Credenciais de integração" subtitle="Somente fingerprint pública, versão e validade."><SimpleTable rows={list("credentials")} columns={[["workspaceName", "Workspace"], ["integration", "Integração"], ["fingerprint", "Fingerprint"], ["version", "Versão"], ["expiresAt", "Expira"]]} dates={new Set(["expiresAt"])} /></Panel>
      <div className={styles.twoColumns}><Panel title="Chaves de API"><SimpleTable rows={list("apiKeys")} columns={[["workspace_name", "Workspace"], ["name", "Nome"], ["prefix", "Prefixo"], ["status", "Status"]]} /></Panel><Panel title="Webhooks"><SimpleTable rows={list("webhooks")} columns={[["workspace_name", "Workspace"], ["name", "Nome"], ["status", "Status"], ["failure_count", "Falhas"]]} /></Panel></div></>}
  </>;
}
function Capability({ title, data }: { title: string; data?: Row }) { const enabled = data?.implemented ?? data?.enabled ?? data?.available; return <Panel title={title}><div className={styles.capability}><Status value={enabled ? "ready" : "unavailable"} /><p>{text(data?.reason) || "Disponibilidade não informada."}</p></div></Panel>; }
function SimpleTable({ rows, columns, dates = new Set<string>() }: { rows: Row[]; columns: [string, string][]; dates?: Set<string> }) { return rows.length ? <div className={styles.tableWrap}><table><thead><tr>{columns.map(([, label]) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.slice(0, 50).map((row, index) => <tr key={text(row.id) || index}>{columns.map(([key]) => <td key={key}>{key === "status" ? <Status value={text(row[key])} /> : dates.has(key) ? date(row[key]) : typeof row[key] === "number" ? number(row[key]) : text(row[key]) || "—"}</td>)}</tr>)}</tbody></table></div> : <Empty />; }
