"use client";

import { FormEvent, useState } from "react";
import { KeyRound, Plus, Save, Settings2, Trash2, Webhook } from "lucide-react";
import styles from "../platform.module.css";
import { AdminAction, AdminActionDialog, Empty, ErrorState, Loading, Notice, Panel, Row, Status, bool, number, platformRequest, text, usePlatformResource } from "./core";

type Ask = (action: string, payload: Row, title: string, consequence: string, confirmLabel?: string) => void;
type Configuration = Row & {
  workspace?: Row; boards?: Row[]; lists?: Row[]; companies?: Row[]; members?: Row[]; labels?: Row[]; fields?: Row[];
  templates?: Row[]; settings?: Row; holidays?: Row[]; sla?: Row[]; rules?: Row[]; modules?: Row[]; memberModuleGrants?: Row[]; apiKeys?: Row[]; webhooks?: Row[];
};

const field = (data: FormData, name: string) => text(data.get(name)).trim();
const values = (data: FormData, name: string) => data.getAll(name).map(text).filter(Boolean);

export function WorkspaceConfiguration({ workspaceId }: { workspaceId: string }) {
  const resource = usePlatformResource<Configuration>(`/api/platform/workspaces/${encodeURIComponent(workspaceId)}/configuration`);
  const [tab, setTab] = useState("identity"); const [action, setAction] = useState<AdminAction | null>(null); const [notice, setNotice] = useState("");
  const ask: Ask = (requestedAction, payload, title, consequence, confirmLabel = "Confirmar alteração") => setAction({
    title, consequence, confirmLabel,
    run: async ({ reason }) => {
      await platformRequest(`/api/platform/workspaces/${encodeURIComponent(workspaceId)}/configuration`, { method: "POST", body: JSON.stringify({ action: requestedAction, payload, reason, confirmed: true }) });
      setNotice(`${title}: alteração aplicada e auditada.`); resource.refresh();
    },
  });
  if (resource.loading && !resource.data) return <Loading label="Carregando configuração administrativa…" />;
  if (resource.error) return <ErrorState message={resource.error} retry={resource.refresh} />;
  const data = resource.data ?? {};
  const revision = JSON.stringify(data);
  return <><div className={styles.configHeading}><div><Settings2 aria-hidden="true" /><span><strong>{text(data.workspace?.name)}</strong><small>{text(data.workspace?.slug)} · alterações com escopo RLS explícito</small></span></div><button type="button" onClick={resource.refresh} disabled={resource.loading}>Atualizar configuração</button></div>
    {notice && <Notice>{notice}</Notice>}
    <div key={revision}><div className={styles.tabs} role="tablist" aria-label="Configuração do workspace">{[["identity", "Grupo e empresas"], ["flow", "Fluxo e metadados"], ["policies", "SLA e automações"], ["access", "Acessos e módulos"], ["endpoints", "API e webhooks"]].map(([key, label]) => <button key={key} type="button" role="tab" aria-selected={tab === key} onClick={() => setTab(key)}>{label}</button>)}</div>
      <div role="tabpanel">
        {tab === "identity" && <IdentityConfiguration data={data} ask={ask} />}
        {tab === "flow" && <FlowConfiguration data={data} ask={ask} />}
        {tab === "policies" && <PolicyConfiguration data={data} ask={ask} />}
        {tab === "access" && <AccessConfiguration data={data} ask={ask} />}
        {tab === "endpoints" && <EndpointConfiguration data={data} ask={ask} />}
      </div>
    </div>
    <AdminActionDialog action={action} onClose={() => setAction(null)} />
  </>;
}

function IdentityConfiguration({ data, ask }: { data: Configuration; ask: Ask }) {
  const workspace = data.workspace ?? {}; const companies = data.companies ?? [];
  function saveWorkspace(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); ask("workspace.update", { name: field(form, "name"), legalName: field(form, "legalName"), taxId: field(form, "taxId"), contactEmail: field(form, "contactEmail"), timezone: field(form, "timezone") }, "Atualizar dados do grupo", "Nome, dados fiscais, contato e fuso serão alterados para todo o workspace."); }
  function addCompany(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); ask("company.save", { legalName: field(form, "legalName"), tradeName: field(form, "tradeName"), taxId: field(form, "taxId"), email: field(form, "email"), phone: field(form, "phone"), parentCompanyId: field(form, "parentCompanyId"), isPrincipal: form.get("isPrincipal") === "on" }, "Cadastrar empresa", "A empresa consumirá o limite contratado e poderá se tornar a principal do grupo.", "Cadastrar empresa"); }
  return <div className={styles.configColumns}><Panel title="Dados do grupo" subtitle="Identificação corporativa usada em todo o workspace."><form className={styles.configForm} onSubmit={saveWorkspace}><label>Nome<input name="name" defaultValue={text(workspace.name)} required minLength={2} /></label><label>Razão social<input name="legalName" defaultValue={text(workspace.legal_name)} /></label><label>CNPJ<input name="taxId" defaultValue={text(workspace.tax_id)} /></label><label>E-mail de contato<input name="contactEmail" type="email" defaultValue={text(workspace.contact_email)} /></label><label>Fuso horário<input name="timezone" defaultValue={text(workspace.timezone) || "America/Sao_Paulo"} /></label><button type="submit"><Save aria-hidden="true" />Revisar alteração</button></form></Panel>
    <Panel title="Empresas e hierarquia" subtitle="A empresa principal é única; inativação preserva histórico."><form className={styles.configForm} onSubmit={addCompany}><label>Razão social<input name="legalName" required /></label><label>Nome fantasia<input name="tradeName" /></label><label>CNPJ<input name="taxId" /></label><label>E-mail<input name="email" type="email" /></label><label>Telefone<input name="phone" /></label><label>Empresa-mãe<select name="parentCompanyId"><option value="">Sem empresa-mãe</option>{companies.map((company) => <option key={text(company.id)} value={text(company.id)}>{text(company.legal_name)}</option>)}</select></label><label className={styles.confirmCheck}><input name="isPrincipal" type="checkbox" />Definir como principal</label><button type="submit"><Plus aria-hidden="true" />Revisar cadastro</button></form><ConfigTable headers={["Empresa", "CNPJ", "Situação", "Ações"]}>{companies.map((company) => <tr key={text(company.id)}><td><strong>{text(company.legal_name)}</strong><small>{text(company.trade_name)}{bool(company.is_principal) ? " · principal" : ""}</small></td><td>{text(company.tax_id) || "—"}</td><td><Status value={text(company.status)} /></td><td><div className={styles.rowActions}>{!bool(company.is_principal) && <button type="button" onClick={() => ask("company.save", { id: company.id, legalName: company.legal_name, tradeName: company.trade_name, taxId: company.tax_id, email: company.email, phone: company.phone, isPrincipal: true }, `Tornar ${text(company.legal_name)} principal`, "A empresa principal atual será vinculada abaixo desta empresa.")}>Tornar principal</button>}<button type="button" data-danger="true" disabled={text(company.status) === "inactive"} onClick={() => ask("company.inactivate", { id: company.id }, `Inativar ${text(company.legal_name)}`, "A empresa deixará de aceitar nova operação; dados e histórico serão preservados.", "Inativar empresa")}>Inativar</button></div></td></tr>)}</ConfigTable></Panel></div>;
}

function FlowConfiguration({ data, ask }: { data: Configuration; ask: Ask }) {
  const boards = data.boards ?? []; const lists = data.lists ?? []; const labels = data.labels ?? []; const fields = data.fields ?? []; const templates = data.templates ?? [];
  const simpleSubmit = (event: FormEvent<HTMLFormElement>, action: string, title: string, consequence: string, transform: (form: FormData) => Row) => { event.preventDefault(); ask(action, transform(new FormData(event.currentTarget)), title, consequence); };
  return <div className={styles.configStack}><Panel title="Quadros e fluxo" subtitle="Quadros novos recebem um fluxo inicial; exclusão é recusada se houver demandas."><form className={styles.configForm} onSubmit={(event) => simpleSubmit(event, "board.save", "Criar quadro", "Um novo quadro e três colunas iniciais serão criados.", (form) => ({ name: field(form, "name"), description: field(form, "description"), boardType: field(form, "boardType") }))}><label>Nome<input name="name" required /></label><label>Tipo<input name="boardType" defaultValue="general" required /></label><label className={styles.fullField}>Descrição<input name="description" /></label><button type="submit"><Plus aria-hidden="true" />Revisar quadro</button></form>{boards.map((board) => <section className={styles.configSubsection} key={text(board.id)}><header><div><strong>{text(board.name)}</strong><small>{text(board.description) || text(board.board_type)}</small></div><button type="button" data-danger="true" onClick={() => ask("board.delete", { id: board.id }, `Excluir quadro ${text(board.name)}`, "A ação só será aceita se não houver demandas e se outro quadro permanecer.", "Excluir quadro")}><Trash2 aria-hidden="true" />Excluir</button></header><form className={styles.compactForm} onSubmit={(event) => simpleSubmit(event, "list.save", `Adicionar coluna em ${text(board.name)}`, "A coluna será adicionada ao final do fluxo.", (form) => ({ boardId: board.id, name: field(form, "name"), slaBehavior: field(form, "slaBehavior") }))}><input name="name" aria-label={`Nome da nova coluna de ${text(board.name)}`} placeholder="Nova coluna" required /><select name="slaBehavior" aria-label="Comportamento do SLA"><option value="running">SLA correndo</option><option value="paused">SLA pausado</option><option value="completed">SLA concluído</option></select><button type="submit">Adicionar</button></form><div className={styles.chipList}>{lists.filter((list) => text(list.board_id) === text(board.id)).map((list) => <span key={text(list.id)}><b>{text(list.name)}</b><small>{text(list.sla_behavior)} · {number(list.card_count)} demandas</small><button type="button" aria-label={`Excluir coluna ${text(list.name)}`} onClick={() => ask("list.delete", { id: list.id }, `Excluir coluna ${text(list.name)}`, "A ação só será aceita se a coluna estiver vazia e outra coluna permanecer.", "Excluir coluna")}>×</button></span>)}</div></section>)}</Panel>
    <div className={styles.configColumns}><CollectionPanel title="Etiquetas" rows={labels} nameKey="name" onAdd={(event) => simpleSubmit(event, "label.save", "Criar etiqueta", "A etiqueta ficará disponível nas demandas deste workspace.", (form) => ({ name: field(form, "name"), color: field(form, "color") }))} fields={<><label>Nome<input name="name" required /></label><label>Cor<select name="color" defaultValue="#2563eb"><option value="#2563eb">Azul</option><option value="#16a34a">Verde</option><option value="#d97706">Âmbar</option><option value="#dc2626">Vermelho</option><option value="#64748b">Cinza</option></select></label></>} onDelete={(row) => ask("label.delete", { id: row.id }, `Excluir etiqueta ${text(row.name)}`, "A etiqueta será removida da configuração do workspace.", "Excluir etiqueta")} />
      <CollectionPanel title="Campos personalizados" rows={fields} nameKey="name" onAdd={(event) => simpleSubmit(event, "field.save", "Criar campo personalizado", "O campo ficará disponível nas demandas; a chave não poderá ser reutilizada no workspace.", (form) => ({ name: field(form, "name"), fieldKey: field(form, "fieldKey"), fieldType: field(form, "fieldType"), options: field(form, "options").split(",").map((item) => item.trim()).filter(Boolean), required: form.get("required") === "on" }))} fields={<><label>Nome<input name="name" required /></label><label>Chave<input name="fieldKey" required pattern="[a-zA-Z0-9_]+" /></label><label>Tipo<select name="fieldType"><option value="text">Texto</option><option value="number">Número</option><option value="date">Data</option><option value="select">Seleção</option></select></label><label>Opções<input name="options" placeholder="Uma, Duas, Três" /></label><label className={styles.confirmCheck}><input name="required" type="checkbox" />Obrigatório</label></>} onDelete={(row) => ask("field.delete", { id: row.id }, `Excluir campo ${text(row.name)}`, "A definição será removida; confirme antes de perder o uso futuro do campo.", "Excluir campo")} />
    </div><Panel title="Templates de processo" subtitle="Checklist e prazo padrão por tipo de processo."><form className={styles.configForm} onSubmit={(event) => simpleSubmit(event, "template.save", "Criar template", "O template ficará disponível para novos processos deste workspace.", (form) => ({ name: field(form, "name"), processType: field(form, "processType"), description: field(form, "description"), checklist: field(form, "checklist").split("\n").map((item) => item.trim()).filter(Boolean), defaultSlaDays: Number(field(form, "defaultSlaDays")) || 3, active: true }))}><label>Nome<input name="name" required /></label><label>Tipo<select name="processType"><option value="ADMISSAO">Admissão</option><option value="FERIAS">Férias</option><option value="RESCISAO">Rescisão</option><option value="OUTROS">Outros</option></select></label><label>Prazo útil<input name="defaultSlaDays" type="number" min="1" max="60" defaultValue="3" /></label><label className={styles.fullField}>Descrição<input name="description" /></label><label className={styles.fullField}>Checklist, uma etapa por linha<textarea name="checklist" rows={4} required /></label><button type="submit"><Plus aria-hidden="true" />Revisar template</button></form><ConfigTable headers={["Template", "Tipo", "Prazo", "Ações"]}>{templates.map((template) => <tr key={text(template.id)}><td><strong>{text(template.name)}</strong><small>{text(template.description)}</small></td><td>{text(template.process_type)}</td><td>{number(template.default_sla_days)} dias úteis</td><td><button className={styles.smallAction} type="button" onClick={() => ask("template.delete", { id: template.id }, `Excluir template ${text(template.name)}`, "O template não ficará disponível para novos processos.", "Excluir template")}>Excluir</button></td></tr>)}</ConfigTable></Panel></div>;
}

function PolicyConfiguration({ data, ask }: { data: Configuration; ask: Ask }) {
  const settings = data.settings ?? {}; const holidays = data.holidays ?? []; const policies = data.sla ?? []; const rules = data.rules ?? [];
  const [jsonError, setJsonError] = useState("");
  function calendar(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); ask("calendar.update", { businessDays: values(form, "businessDays").map(Number), dayStart: field(form, "dayStart"), dayEnd: field(form, "dayEnd"), realtimeSeconds: Number(field(form, "realtimeSeconds")) }, "Atualizar calendário e expediente", "O cálculo futuro de SLA usará os novos dias e horários úteis."); }
  function holiday(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); ask("holiday.save", { date: field(form, "date"), name: field(form, "name") }, "Cadastrar feriado", "A data deixará de contar como dia útil nos SLAs.", "Cadastrar feriado"); }
  function sla(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); ask("sla.save", { processType: field(form, "processType"), targetBusinessDays: Number(field(form, "target")), warningBusinessDays: Number(field(form, "warning")), active: true }, "Atualizar política de SLA", "Novas medições usarão a meta e o alerta configurados."); }
  function rule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); let condition: Row; let ruleAction: Row; try { condition = JSON.parse(field(form, "condition") || "{}"); ruleAction = JSON.parse(field(form, "ruleAction") || "{}"); setJsonError(""); } catch { setJsonError("Condição e ação precisam ser objetos JSON válidos."); return; } ask("rule.save", { name: field(form, "name"), trigger: field(form, "trigger"), condition, ruleAction, enabled: true }, "Criar automação", "A regra será avaliada para novos eventos do gatilho escolhido.", "Criar automação"); }
  const businessDays = Array.isArray(settings.business_days) ? settings.business_days.map(Number) : [1, 2, 3, 4, 5];
  return <div className={styles.configColumns}><Panel title="Expediente e feriados" subtitle="Base temporal usada pelo cálculo de SLA."><form className={styles.configForm} onSubmit={calendar}><fieldset className={styles.fullField}><legend>Dias úteis</legend><div className={styles.dayChecks}>{["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"].map((label, day) => <label key={label}><input name="businessDays" type="checkbox" value={day} defaultChecked={businessDays.includes(day)} />{label}</label>)}</div></fieldset><label>Início<input name="dayStart" type="time" defaultValue={text(settings.day_start) || "08:00"} /></label><label>Fim<input name="dayEnd" type="time" defaultValue={text(settings.day_end) || "18:00"} /></label><label>Atualização (seg.)<input name="realtimeSeconds" type="number" min="5" max="120" defaultValue={number(settings.realtime_seconds) || 30} /></label><button type="submit"><Save aria-hidden="true" />Revisar calendário</button></form><form className={styles.compactForm} onSubmit={holiday}><input name="date" type="date" aria-label="Data do feriado" required /><input name="name" aria-label="Nome do feriado" placeholder="Nome do feriado" required /><button type="submit">Adicionar</button></form><div className={styles.chipList}>{holidays.map((item) => <span key={text(item.holiday_date)}><b>{text(item.name)}</b><small>{text(item.holiday_date)}</small><button type="button" onClick={() => ask("holiday.delete", { date: item.holiday_date }, `Excluir feriado ${text(item.name)}`, "A data voltará a contar como dia útil.", "Excluir feriado")}>×</button></span>)}</div></Panel>
    <Panel title="Políticas de SLA" subtitle="Metas em dias úteis por processo."><form className={styles.configForm} onSubmit={sla}><label>Processo<select name="processType"><option value="ADMISSAO">Admissão</option><option value="FERIAS">Férias</option><option value="RESCISAO">Rescisão</option><option value="OUTROS">Outros</option></select></label><label>Meta<input name="target" type="number" min="1" max="60" defaultValue="3" /></label><label>Alerta<input name="warning" type="number" min="0" max="60" defaultValue="1" /></label><button type="submit">Revisar política</button></form><ConfigTable headers={["Processo", "Meta", "Alerta"]}>{policies.map((policy) => <tr key={text(policy.id)}><td>{text(policy.process_type)}</td><td>{number(policy.target_business_days)} dias</td><td>{number(policy.warning_business_days)} dias</td></tr>)}</ConfigTable></Panel>
    <Panel title="Automações administrativas" subtitle="Somente condições do gatilho e ações executadas pelo backend são aceitas."><form className={styles.configForm} onSubmit={rule}><label>Nome<input name="name" required /></label><label>Gatilho<select name="trigger"><option value="card.created">Demanda criada</option><option value="card.moved">Demanda movida</option><option value="assignee.added">Responsável atribuído</option><option value="checklist.completed">Checklist concluído</option><option value="sla.tick">Verificação de SLA</option></select></label><label className={styles.fullField}>Condição JSON <small>Campos aceitos dependem do gatilho: processType/priority, listKind/fromListKind, assignee ou allItems.</small><textarea name="condition" defaultValue="{}" rows={3} required /></label><label className={styles.fullField}>Ação JSON <small>Use moveTo, slaStatus ou labelId; identificadores são validados neste workspace.</small><textarea name="ruleAction" defaultValue={'{"slaStatus":"recalculate"}'} rows={3} required /></label>{jsonError && <p className={`${styles.dialogError} ${styles.fullField}`} role="alert">{jsonError}</p>}<button type="submit"><Plus aria-hidden="true" />Revisar automação</button></form><ConfigTable headers={["Regra", "Gatilho", "Estado", "Ações"]}>{rules.map((item) => <tr key={text(item.id)}><td>{text(item.name)}</td><td>{text(item.trigger)}</td><td><Status value={bool(item.enabled) ? "active" : "paused"} /></td><td><button type="button" className={styles.smallAction} onClick={() => ask("rule.delete", { id: item.id }, `Excluir automação ${text(item.name)}`, "A regra deixará de executar para novos eventos.", "Excluir automação")}>Excluir</button></td></tr>)}</ConfigTable></Panel></div>;
}

function AccessConfiguration({ data, ask }: { data: Configuration; ask: Ask }) {
  const members = data.members ?? []; const companies = data.companies ?? []; const modules = data.modules ?? []; const memberModuleGrants = data.memberModuleGrants ?? [];
  function member(event: FormEvent<HTMLFormElement>, row: Row) { event.preventDefault(); const form = new FormData(event.currentTarget); ask("member.scope", { userId: row.user_id, role: field(form, "role"), companyIds: values(form, "companyIds") }, `Atualizar acesso de ${text(row.name)}`, "Papel e empresas permitidas serão substituídos pelos valores selecionados."); }
  function module(event: FormEvent<HTMLFormElement>, row: Row) { event.preventDefault(); const form = new FormData(event.currentTarget); const selected = field(form, "grant"); ask("module.set", { moduleKey: row.key, granted: selected === "inherit" ? null : selected === "allow" }, `Atualizar módulo ${text(row.name)}`, "A regra individual do workspace prevalece sobre a concessão herdada do plano."); }
  function memberModule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const selected = field(form, "grant"); const userId = field(form, "userId"); const moduleKey = field(form, "moduleKey"); const memberName = text(members.find((item) => text(item.user_id) === userId)?.name); const moduleName = text(modules.find((item) => text(item.key) === moduleKey)?.name); ask("member.module.set", { userId, moduleKey, granted: selected === "inherit" ? null : selected === "allow" }, `Atualizar ${moduleName} para ${memberName}`, "A negação individual vence o papel; uma liberação individual nunca vence o plano do workspace."); }
  return <div className={styles.configStack}><div className={styles.configColumns}><Panel title="Usuários e empresas permitidas" subtitle="O proprietário não pode ser rebaixado; papéis atuais são preservados.">{members.map((row) => <form className={styles.accessRow} key={text(row.user_id)} onSubmit={(event) => member(event, row)}><div><strong>{text(row.name)}</strong><small>{text(row.email)}</small></div><label>Papel<select name="role" defaultValue={text(row.role)}><option value="admin">Administrador</option><option value="member">Membro</option><option value="observer">Observador</option><option value="guest">Convidado</option></select></label><fieldset><legend>Empresas permitidas</legend>{companies.map((company) => <label key={text(company.id)}><input name="companyIds" type="checkbox" value={text(company.id)} defaultChecked={(Array.isArray(row.company_ids) ? row.company_ids : []).map(text).includes(text(company.id))} />{text(company.trade_name) || text(company.legal_name)}</label>)}</fieldset><button type="submit"><Save aria-hidden="true" />Revisar acesso</button></form>)}</Panel>
      <Panel title="Módulos do workspace" subtitle="Negação explícita vence o plano; herdar remove a exceção.">{modules.map((row) => <form className={styles.moduleRow} key={text(row.key)} onSubmit={(event) => module(event, row)}><div><strong>{text(row.name)}</strong><small>{text(row.category)} · plano: {bool(row.in_plan) ? "incluído" : "não incluído"}</small></div><select name="grant" defaultValue={row.granted == null ? "inherit" : bool(row.granted) ? "allow" : "deny"} aria-label={`Permissão do módulo ${text(row.name)}`}><option value="inherit">Herdar do plano</option><option value="allow">Liberar</option><option value="deny">Bloquear</option></select><button type="submit">Revisar</button></form>)}</Panel></div>
    <Panel title="Exceção individual de módulo" subtitle="Matriz usuário × workspace × empresa × módulo: o escopo de empresas está acima e a exceção de módulo é aplicada aqui."><form className={styles.configForm} onSubmit={memberModule}><label>Usuário<select name="userId" required><option value="">Selecione</option>{members.map((item) => <option key={text(item.user_id)} value={text(item.user_id)}>{text(item.name)} · {text(item.email)}</option>)}</select></label><label>Módulo<select name="moduleKey" required><option value="">Selecione</option>{modules.map((item) => <option key={text(item.key)} value={text(item.key)}>{text(item.name)}</option>)}</select></label><label>Decisão<select name="grant"><option value="inherit">Herdar do papel</option><option value="allow">Liberar leitura</option><option value="deny">Bloquear</option></select></label><button type="submit">Revisar exceção</button></form><ConfigTable headers={["Usuário", "Módulo", "Decisão", "Motivo anterior"]}>{memberModuleGrants.map((grant) => <tr key={`${text(grant.user_id)}:${text(grant.module_key)}`}><td>{text(members.find((item) => text(item.user_id) === text(grant.user_id))?.name) || text(grant.user_id)}</td><td>{text(modules.find((item) => text(item.key) === text(grant.module_key))?.name) || text(grant.module_key)}</td><td><Status value={bool(grant.granted) ? "allowed" : "blocked"} /></td><td>{text(grant.reason)}</td></tr>)}</ConfigTable>{!memberModuleGrants.length && <Empty>Nenhuma exceção individual; todos seguem papel e plano.</Empty>}</Panel></div>;
}

function EndpointConfiguration({ data, ask }: { data: Configuration; ask: Ask }) {
  const keys = data.apiKeys ?? []; const webhooks = data.webhooks ?? [];
  return <div className={styles.configColumns}><Panel title="Chaves de API" subtitle="Somente prefixo e metadados seguros são retornados. Valores e hashes nunca saem do servidor."><div className={styles.inlineWarning}><KeyRound aria-hidden="true" />Provisionamento de segredo exige canal seguro fora desta tela; aqui é possível auditar e revogar chaves existentes.</div><ConfigTable headers={["Chave", "Prefixo", "Estado", "Ações"]}>{keys.map((row) => <tr key={text(row.id)}><td><strong>{text(row.name)}</strong><small>Último uso: {text(row.last_used_at) || "nunca"}</small></td><td><code>{text(row.prefix)}</code></td><td><Status value={text(row.status)} /></td><td><button type="button" className={styles.smallAction} disabled={text(row.status) === "revoked"} onClick={() => ask("api_key.revoke", { id: row.id }, `Revogar chave ${text(row.name)}`, "A chave deixará de autenticar imediatamente; o valor não poderá ser recuperado.", "Revogar chave")}>Revogar</button></td></tr>)}</ConfigTable>{!keys.length && <Empty>Nenhuma chave de API provisionada.</Empty>}</Panel>
    <Panel title="Webhooks" subtitle="Status, falhas e destino são visíveis; segredo e assinatura nunca são retornados."><div className={styles.inlineWarning}><Webhook aria-hidden="true" />Rotação de segredo não é exposta sem um fluxo de entrega segura ao consumidor.</div><ConfigTable headers={["Endpoint", "Falhas", "Estado", "Ações"]}>{webhooks.map((row) => <tr key={text(row.id)}><td><strong>{text(row.name)}</strong><small>{text(row.url)}</small></td><td>{number(row.failed_deliveries)}</td><td><Status value={text(row.status)} /></td><td><div className={styles.rowActions}>{text(row.status) !== "active" && <button type="button" onClick={() => ask("webhook.status", { id: row.id, status: "active" }, `Ativar webhook ${text(row.name)}`, "Novas entregas voltarão a ser enviadas.", "Ativar webhook")}>Ativar</button>}{text(row.status) === "active" && <button type="button" onClick={() => ask("webhook.status", { id: row.id, status: "paused" }, `Pausar webhook ${text(row.name)}`, "Novas entregas ficarão suspensas até reativação.", "Pausar webhook")}>Pausar</button>}<button type="button" data-danger="true" disabled={text(row.status) === "disabled"} onClick={() => ask("webhook.status", { id: row.id, status: "disabled" }, `Desabilitar webhook ${text(row.name)}`, "Entregas pendentes serão canceladas e o endpoint permanecerá inativo.", "Desabilitar webhook")}>Desabilitar</button></div></td></tr>)}</ConfigTable>{!webhooks.length && <Empty>Nenhum webhook configurado.</Empty>}</Panel></div>;
}

function CollectionPanel({ title, rows, nameKey, fields, onAdd, onDelete }: { title: string; rows: Row[]; nameKey: string; fields: React.ReactNode; onAdd: (event: FormEvent<HTMLFormElement>) => void; onDelete: (row: Row) => void }) {
  return <Panel title={title}><form className={styles.configForm} onSubmit={onAdd}>{fields}<button type="submit"><Plus aria-hidden="true" />Revisar cadastro</button></form><div className={styles.simpleRows}>{rows.map((row) => <div key={text(row.id)}><span><strong>{text(row[nameKey])}</strong><small>{text(row.field_type ?? row.color)}</small></span><button type="button" onClick={() => onDelete(row)}>Excluir</button></div>)}</div>{!rows.length && <Empty />}</Panel>;
}

function ConfigTable({ headers, children }: { headers: string[]; children: React.ReactNode }) {
  return <div className={styles.tableWrap}><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
}
