/**
 * ARQUIVO GERADO — não edite à mão.
 *
 * Lista das migrations que esta versão do aplicativo espera encontrar aplicadas.
 * Regenerar com: npm run schema:manifest
 */
export const expectedMigrations = [
  "0000_romantic_ken_ellis.sql",
  "0001_0_prepare_legacy_defaults.sql",
  "0001_normalize_existing_neon.sql",
  "0001_z_restore_timestamp_defaults.sql",
  "0002_chief_venom.sql",
  "0003_revocable_sessions_and_solides_boundary.sql",
  "0004_auth_rate_limits.sql",
  "0005_tenant_integrity_constraints.sql",
  "0006_bootstrap_guard.sql",
  "0007_companies_rls.sql",
  "0008_direct_workspace_rls.sql",
  "0009_webhook_tenant_rls.sql",
  "0010_child_tenant_rls.sql",
  "0011_session_management.sql",
  "0012_structured_audit.sql",
  "0013_registrations_foundation.sql",
  "0014_operation_dp_foundation.sql",
  "0015_auxiliary_modules_foundation.sql",
  "0016_integrations_engine.sql",
  "0017_saas_foundation.sql",
  "0018_payment_control_modules.sql",
  "0019_outbox_webhooks_public_api.sql",
  "0020_marketing_leads.sql",
  "0021_time_tracking.sql",
  "0022_plan_catalog_pricing.sql",
  "0023_platform_lifecycle.sql",
  "0024_module_catalog.sql",
  "0025_access_module.sql",
  "0026_caju_templates.sql",
  "0027_caju_template_format.sql",
  "0028_solides_admission_connector.sql",
  "0029_tangerino_connector.sql",
  "0030_bootstrap_guard_deferrable.sql",
  "0031_caju_template_source.sql",
  "0032_contractor_registry.sql",
  "0033_member_module_grants.sql",
  "0034_workspace_deletion_ledger.sql",
  "0035_assistant_conversations.sql",
  "0036_platform_console_indexes.sql",
  "0037_integration_events_and_workspace_lifecycle.sql",
  "0038_sankhya_browser_connector.sql",
  "0039_attachment_storage_quota_index.sql",
  "0040_auth_events.sql",
  "0041_obligation_protocol_evidence.sql",
  "0042_member_company_access_rls.sql",
  "0043_lead_privacy_interest.sql",
  "0044_epi_control.sql",
  "0045_workspace_areas_shared_stock.sql",
  "0046_department_module_backfill.sql",
  "0047_group_owned_epi_products.sql",
  "0048_epi_compliance.sql",
] as const;

/** Última migration conhecida por esta versão. */
export const latestMigration = expectedMigrations[expectedMigrations.length - 1];
